#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 6052-webs
    bind *:80
    mode http
    balance round-robin
    server 6097-web-01 3.89.224.227:80 check
    server 6097-"web-02" 54.242.83.27:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
